// src/components/Comment.tsx
import type { ReactNode } from "react";
import { useAppContext } from "../AppContext";
import CodeLine from "./CodeLine";
import { formatCodeElements } from "./FormatCode";
import Tab from "./Tab";

export default function Comment({
  indentation,
  comment,
  children,
}: {
  indentation?: number;
  comment: string;
  children?: ReactNode;
}) {
  const { languageHelper } = useAppContext();

  return (
    <CodeLine>
      {indentation != null && Array.from({ length: indentation }, (_, i) => <Tab key={i} />)}
      <span className="comment">{formatCodeElements(`${languageHelper.comment} ${comment}`)}</span>
      {children}
    </CodeLine>
  );
}

// src/views/_comment.vue
<template>
  <CodeLine>
    <Tab v-for="i in indentation" :key="i"/>
    <span class="comment" v-html="commentBody"></span>
    <slot/>
  </CodeLine>
</template>

<script lang="ts">
  import { formatCode } from '../util';

  import CodeLine from './_code_line.vue';
  import Tab from './_tab.vue';

  export default {
    props: [
      'indentation',
      'comment',
    ],
    components: {
      CodeLine,
      Tab,
    },
    computed: {
      commentBody() {
        return formatCode(`// ${this.comment}`);
      },
    },
  };
</script>
