// src/components/MultiLineString.tsx
import { useMemo } from "react";
import CodeLine from "./CodeLine";
import { formatCodeElements } from "./FormatCode";
import Tab from "./Tab";

export default function MultiLineString({
  indentation,
  value,
}: {
  indentation: number;
  value: string;
}) {
  const lines = useMemo(() => value.split("\n").map((str: string) => str.trim()), [value]);

  return (
    <div className="multi-line-string">
      {lines.map((line, index) => (
        <CodeLine key={index}>
          {Array.from({ length: indentation }, (_, i) => (
            <Tab key={i} />
          ))}
          <span className="string">{formatCodeElements(line)}</span>
        </CodeLine>
      ))}
    </div>
  );
}

// src/views/_multi_line_string.vue
<template>
  <div class="multi-line-string">
    <CodeLine v-for="(line, index) in lines" :key="index">
      <Tab v-for="i in indentation" :key="i" /><span class="string" v-html="line"></span>
    </CodeLine>
  </div>
</template>

<script lang="ts">
import { formatCode } from '../util';

import CodeLine from './_code_line.vue';
import Tab from './_tab.vue';

export default {
  props: ['indentation', 'value'],
  computed: {
    lines() {
      return this.value.split('\n').map((str: string) => formatCode(str.trim()));
    },
  },
  components: {
    CodeLine,
    Tab,
  },
};
</script>
