// src/components/Profile.tsx
import { useMemo } from "react";
import { Section as SectionEnum } from "../data_types";
import CodeLine from "./CodeLine";
import Section from "./Section";
import StringValue from "./StringValue";
import Url from "./Url";
import Variable from "./Variable";

interface ProfileData {
  myName: string;
  profession: string;
  emails: string[];
  socialNetworks: { [key: string]: string };
}

export default function Profile({ data }: { data: ProfileData }) {
  const email = useMemo(() => {
    return data.emails[Math.floor(Math.random() * data.emails.length)];
  }, [data.emails]);

  return (
    <div className="profile">
      <Section section={SectionEnum.Profile} />
      <CodeLine />
      <Variable name="myName">
        <StringValue value={data.myName} />
      </Variable>
      <Variable name="profession">
        <StringValue value={data.profession} />
      </Variable>
      <Variable name="email">
        <StringValue value={email} />
      </Variable>
      <CodeLine />
      {Object.entries(data.socialNetworks).map(([name, url]) => (
        <Variable key={name} name={name}>
          <Url value={url} />
        </Variable>
      ))}
      <CodeLine />
      <CodeLine />
    </div>
  );
}

// src/views/_profile.vue
<template>
  <div class="profile">
    <Section :section="Section.Profile"></Section>
    <CodeLine />
    <Variable name="myName">
      <String :value="data.myName"></String>
    </Variable>
    <Variable name="profession">
      <String :value="data.profession"></String>
    </Variable>
    <Variable name="email">
      <String :value="email"></String>
    </Variable>
    <CodeLine />
    <Variable v-for="(url, name) in data.socialNetworks" :key="name" :name="name">
      <Url :value="url"></Url>
    </Variable>
    <CodeLine />
    <CodeLine />
  </div>
</template>

<script lang="ts">
import { track } from '../util';

import CodeLine from './_code_line.vue';
import Variable from './_variable.vue';
import String from './_string.vue';
import Url from './_url.vue';
import Section from './_section.vue';

export default {
  props: ['data'],
  computed: {
    email() {
      const emails = this.data.emails;
      return emails[Math.floor(Math.random() * emails.length)];
    },
  },
  components: {
    CodeLine,
    Variable,
    String,
    Url,
    Section,
  },
};
</script>
