// src/components/ShowCaseSection.tsx
import { useAppContext } from "../AppContext";
import type { Section as SectionEnum, ShowCase as ShowCaseType } from "../data_types";
import CodeLine from "./CodeLine";
import Section from "./Section";
import ShowCase from "./ShowCase";

export default function ShowCaseSection({
  section,
  name,
  data,
}: {
  section: SectionEnum;
  name: string;
  data: ShowCaseType[];
}) {
  const { isJs, isTs } = useAppContext();

  return (
    <div>
      <Section section={section} />
      <CodeLine />
      <CodeLine>
        {isJs && <span className="storage-type">const</span>}
        {isJs && <span className="white-space space"></span>}
        <span className="variable">{name}</span>
        {isTs && <span className="keyword">:</span>}
        {isTs && <span className="white-space space"></span>}
        {isTs && <span className="type class">ShowCase</span>}
        {isTs && <span className="expression">[]</span>}
        <span className="white-space space"></span>
        <span className="expression">=</span>
        <span className="white-space space"></span>
        <span className="expression">[</span>
      </CodeLine>
      {data.map((entry, index) => (
        <ShowCase key={index} data={entry} isLast={index === data.length - 1} />
      ))}
      <CodeLine>
        <span className="expression">];</span>
      </CodeLine>
      <CodeLine />
      <CodeLine />
    </div>
  );
}

// src/views/_show_case_section.vue
<template>
  <div>
    <Section :section="section"></Section>
    <CodeLine />
    <CodeLine>
      <span class="storage-type" v-if="isJs">const</span>
      <span class="white-space space" v-if="isJs"></span>
      <span class="variable">{{ name }}</span>
      <span class="keyword" v-if="isTs">:</span>
      <span class="white-space space" v-if="isTs"></span>
      <span class="type class" v-if="isTs">ShowCase</span>
      <span class="expression" v-if="isTs">[]</span>
      <span class="white-space space"></span>
      <span class="expression">=</span>
      <span class="white-space space"></span>
      <span class="expression">[</span>
    </CodeLine>
    <template v-for="(entry, index) in data">
      <ShowCase :key="`show-case-${index}`" :data="entry" :isLast="index === data.length - 1" />
    </template>
    <CodeLine>
      <span class="expression">];</span>
    </CodeLine>
    <CodeLine />
    <CodeLine />
  </div>
</template>

<script lang="ts">
import CodeLine from './_code_line.vue';
import Section from './_section.vue';
import ShowCase from './_show_case.vue';

export default {
  props: ['section', 'name', 'data'],
  components: {
    CodeLine,
    Section,
    ShowCase,
  },
};
</script>
