// src/components/SkillSet.tsx
import { useState } from "react";
import type { SkillSet as SkillSetType, Skill as SkillType } from "../data_types";
import CodeLine from "./CodeLine";
import Collapsed from "./Collapsed";
import Comment from "./Comment";
import Skill from "./Skill";

export default function SkillSet({ title, skillset }: { title: string; skillset: SkillSetType }) {
  const [collapsed, setCollapsed] = useState(true);

  const toggle = (e: React.MouseEvent) => {
    e.stopPropagation();
    setCollapsed((c) => !c);
  };

  return (
    <div className={`skillset${collapsed ? " collapsed" : ""}`} onClick={toggle}>
      <Comment comment={title}>{collapsed && <Collapsed />}</Comment>
      {!collapsed && (
        <>
          {Array.isArray(skillset.data)
            ? (skillset.data as SkillSetType[]).map((subset) => (
                <SkillSet
                  key={subset.title}
                  title={`${title} / ${subset.title}`}
                  skillset={subset}
                />
              ))
            : Object.entries(skillset.data as { [key: string]: SkillType }).map(([name, skill]) => (
                <Skill key={name} name={name} skill={skill} />
              ))}
          <CodeLine />
        </>
      )}
    </div>
  );
}

// src/views/_skill_set.vue
<template>
  <div class="skillset" @click.stop="toggle" :class="{ collapsed: collapsed }">
    <Comment :comment="title"><Collapsed v-if="collapsed"/></Comment>
    <template v-if="!collapsed">
      <template v-if="Array.isArray(skillset.data)">
        <SkillSet
          v-for="subset in skillset.data"
          :title="title + ' / ' + subset.title"
          :skillset="subset"
          :key="subset.title"
        />
      </template>
      <template v-else v-for="(skill, name) in skillset.data">
        <Skill
          :name="name"
          :skill="skill"
          :key="name"
        />
      </template>
      <CodeLine/>
    </template>
  </div>
</template>

<script lang="ts">
  import CodeLine from './_code_line.vue';
  import Skill from './_skill.vue';
  import Comment from './_comment.vue';
  import Collapsed from './_collapsed.vue';

  export default {
    name: 'SkillSet',
    data() {
      return {
        collapsed: true,
      };
    },
    props: [
      'title',
      'skillset',
    ],
    methods: {
      toggle() {
        this.collapsed = !this.collapsed;
      },
    },
    components: {
      CodeLine,
      Skill,
      Comment,
      Collapsed,
    },
  };
</script>
