// src/components/Skill.tsx
import { useAppContext } from "../AppContext";
import type { Skill as SkillType } from "../data_types";
import NumberValue from "./NumberValue";
import StringValue from "./StringValue";
import Variable from "./Variable";

export default function Skill({ name, skill }: { name: string; skill: SkillType }) {
  const { isRuby } = useAppContext();

  return (
    <Variable name={name} type="Skill" length={16}>
      <span className="expression">{"{"}</span>
      <span className="white-space space"></span>
      <span className="variable">level</span>
      <span className="expression">:</span>
      <span className="white-space space"></span>
      <NumberValue value={skill.level.toFixed(1)} className="progress" />
      <span className="expression">,</span>
      <span className="white-space space"></span>
      <span className="variable">name</span>
      <span className="expression">:</span>
      <span className="white-space space"></span>
      <StringValue value={skill.name} />
      <span className="white-space space"></span>
      <span className="expression">{"}"}</span>
      {isRuby && <span className="variable">.with_indifferent_access</span>}
    </Variable>
  );
}

// src/views/_skill.vue
<template>
  <Variable :name="name" type="Skill" :length="16">
    <span class="expression">{</span>
    <span class="white-space space"></span>
    <span class="variable">level</span>
    <span class="expression">:</span>
    <span class="white-space space"></span>
    <Number :value="skill.level.toFixed(1)" class="progress" />
    <span class="expression">,</span>
    <span class="white-space space"></span>
    <span class="variable">name</span>
    <span class="expression">:</span>
    <span class="white-space space"></span>
    <String :value="skill.name"></String>
    <span class="white-space space"></span>
    <span class="expression">}</span>
    <span class="variable" v-if="isRuby">.with_indifferent_access</span>
  </Variable>
</template>

<script lang="ts">
  import Variable from './_variable.vue';
  import String from './_string.vue';
  import Number from './_number.vue';

  export default {
    props: [
      'name',
      'skill',
    ],
    components: {
      Variable,
      String,
      Number,
    },
  };
</script>
