// src/components/Stage.tsx
import { type ReactNode, useState } from "react";
import { useAppContext } from "../AppContext";
import type { Stage as StageType } from "../data_types";
import CodeLine from "./CodeLine";
import Collapsed from "./Collapsed";
import Comment from "./Comment";
import DateValue from "./DateValue";
import MultiLineString from "./MultiLineString";
import Tab from "./Tab";
import VariableName from "./VariableName";

export default function Stage({
  data,
  abbreviation,
  isLast,
  className,
  children,
}: {
  data: StageType;
  abbreviation: string;
  isLast: boolean;
  className?: string;
  children?: ReactNode;
}) {
  const [collapsed, setCollapsed] = useState(true);
  const { isRuby, languageHelper } = useAppContext();

  const toggle = (e: React.MouseEvent) => {
    e.stopPropagation();
    setCollapsed((c) => !c);
  };

  return (
    <div
      className={`stage${collapsed ? " collapsed" : ""}${className ? ` ${className}` : ""}`}
      onClick={toggle}
    >
      {collapsed ? (
        <Comment indentation={1} comment={abbreviation}>
          <Collapsed />
        </Comment>
      ) : (
        <>
          <CodeLine>
            <Tab />
            <span className="expression">{"{"}</span>
          </CodeLine>
          {children}
          {data.description && (
            <>
              <CodeLine>
                <Tab />
                <Tab />
                <span className="variable">description</span>
                <span className="expression">:</span>
                <span className="white-space space"></span>
                <span className="string">{languageHelper.multilineString}</span>
              </CodeLine>
              <MultiLineString value={data.description.trim()} indentation={3} />
              <CodeLine>
                <Tab />
                <Tab />
                <span className="string">{languageHelper.multilineString}</span>
                <span className="expression">,</span>
              </CodeLine>
            </>
          )}
          <CodeLine>
            <Tab />
            <Tab />
            <VariableName name="startsAt" />
            <span className="expression">:</span>
            <span className="white-space space"></span>
            <DateValue value={data.startsAt} />
            <span className="expression">,</span>
          </CodeLine>
          <CodeLine>
            <Tab />
            <Tab />
            <VariableName name="endsAt" />
            <span className="expression">:</span>
            <span className="white-space space"></span>
            <DateValue value={data.endsAt} />
            <span className="expression">,</span>
          </CodeLine>
          <CodeLine>
            <Tab />
            <Tab />
            <VariableName name="skills" />
            <span className="expression">:</span>
            <span className="white-space space"></span>
            <span className="expression">[</span>
          </CodeLine>
          {Object.entries(data.skills).map(([key, skill]) => (
            <CodeLine key={key}>
              <Tab />
              <Tab />
              <Tab />
              <span
                className="variable progress"
                style={{ "--value": skill.level } as React.CSSProperties}
              >
                {key}
              </span>
              <span className="expression">,</span>
            </CodeLine>
          ))}
          <CodeLine>
            <Tab />
            <Tab />
            <span className="expression">],</span>
          </CodeLine>
          <CodeLine>
            <Tab />
            <span className="expression">{"}"}</span>
            {isRuby && <span className="expression">.with_indifferent_access</span>}
            <span className="expression">,</span>
          </CodeLine>
          {!isLast && <CodeLine />}
        </>
      )}
    </div>
  );
}

// src/views/_stage.vue
<template>
  <div class="stage" @click.stop="toggle" :class="{ collapsed: collapsed }">
    <Comment :indentation="1" v-if="collapsed" :comment="abbreviation">
      <Collapsed />
    </Comment>
    <template v-if="!collapsed">
      <CodeLine>
        <Tab />
        <span class="expression">{</span>
      </CodeLine>
      <slot />
      <template v-if="data.description">
        <CodeLine>
          <Tab /><Tab />
          <span class="variable">description</span>
          <span class="expression">:</span>
          <span class="white-space space"></span>
          <span class="string">
            {{ state.currentLanguageHelper.multilineString }}
          </span>
        </CodeLine>
        <MultiLineString :value="data.description.trim()" :indentation="3" />
        <CodeLine>
          <Tab /><Tab />
          <span class="string">
            {{ state.currentLanguageHelper.multilineString }}
          </span>
          <span class="expression">,</span>
        </CodeLine>
      </template>
      <CodeLine>
        <Tab /><Tab />
        <VariableName name="startsAt" />
        <span class="expression">:</span>
        <span class="white-space space"></span>
        <Date :value="data.startsAt"></Date>
        <span class="expression">,</span>
      </CodeLine>
      <CodeLine>
        <Tab /><Tab />
        <VariableName name="endsAt" />
        <span class="expression">:</span>
        <span class="white-space space"></span>
        <Date :value="data.endsAt"></Date>
        <span class="expression">,</span>
      </CodeLine>
      <CodeLine>
        <Tab /><Tab />
        <VariableName name="skills" />
        <span class="expression">:</span>
        <span class="white-space space"></span>
        <span class="expression">[</span>
      </CodeLine>
      <CodeLine v-for="(skill, key) in data.skills" :key="key">
        <Tab /><Tab /><Tab />
        <span class="variable progress" :style="{ '--value': skill.level }">{{ key }}</span>
        <span class="expression">,</span>
      </CodeLine>
      <CodeLine>
        <Tab /><Tab />
        <span class="expression">],</span>
      </CodeLine>
      <CodeLine>
        <Tab />
        <span class="expression">}</span>
        <span class="expression" v-if="isRuby">.with_indifferent_access</span>
        <span class="expression">,</span>
      </CodeLine>
      <CodeLine v-if="!isLast" />
    </template>
  </div>
</template>

<script lang="ts">
import { track } from '../util';

import CodeLine from './_code_line.vue';
import Comment from './_comment.vue';
import Tab from './_tab.vue';
import String from './_string.vue';
import MultiLineString from './_multi_line_string.vue';
import Date from './_date.vue';
import Collapsed from './_collapsed.vue';
import VariableName from './_variable_name.vue';

export default {
  data() {
    return {
      collapsed: true,
    };
  },
  props: ['isLast', 'data', 'abbreviation'],
  methods: {
    toggle() {
      this.collapsed = !this.collapsed;
      track((this.collapsed ? 'Close' : 'Open') + 'Stage', this.abbreviation);
    },
  },
  computed: {
    multiStringStart() {
      this.collapsed = !this.collapsed;
      track((this.collapsed ? 'Close' : 'Open') + 'Stage', this.abbreviation);
    },
  },
  components: {
    CodeLine,
    Comment,
    Tab,
    String,
    MultiLineString,
    Date,
    Collapsed,
    VariableName,
  },
};
</script>
