// src/components/Url.tsx
import { useMemo } from "react";

export default function Url({ value }: { value: string }) {
  const display = useMemo(() => {
    if (value.length > 70) {
      return value.replace("http://", "").replace("https://", "");
    }
    return value;
  }, [value]);

  return (
    <span className="string">
      {"'"}
      <a href={value} target="_blank" rel="noreferrer">
        {display}
      </a>
      {"'"}
    </span>
  );
}

// src/views/_url.vue
<template>
  <span class="string">
    '<a :href="value" target="_blank">{{display}}</a>'
  </span>
</template>

<script lang="ts">
  import { formatCode } from '../util';

  export default {
    props: [
      'value',
    ],
    computed: {
      display() {
        if (this.value.length > 70) {
          return this.value.replace('http://', '').replace('https://', '');
        }
        return this.value;
      },
    },
  };
</script>
