// src/views/_comment_block.vue
<template>
  <div class="comment-block">
    <CodeLine>
      <span class="comment">{{header}}</span>
    </CodeLine>
    <CodeLine v-for="(comment, index) in comments" :key="index">
      <span class="comment" v-html="comment"></span>
    </CodeLine>
    <CodeLine>
      <span class="comment">{{footer}}</span>
    </CodeLine>
  </div>
</template>

<script lang="ts">
  import { formatCode, center } from '../util';

  import CodeLine from './_code_line.vue';

  export default {
    props: [
      'comment',
    ],
    computed: {
      comments() {
        const len = this.longestLine;

        return this.lines
          .map((str: string) => center(str, len))
          .map(formatCode)
          .map((str: string) =>
            this.currentLanguageHelper.commentChar +
            ' ' + str + ' ' +
            this.currentLanguageHelper.commentChar
          )
        ;
      },
      lines() {
        return this.comment.split('\n');
      },
      longestLine() {
        return Math.max(...this.lines.map((str: string) => str.length));
      },
      header() {
        return this.currentLanguageHelper.commentEnd +
          new Array(this.longestLine + 4)
            .join(this.currentLanguageHelper.commentChar);
      },
      footer() {
        return new Array(this.longestLine + 4)
          .join(this.currentLanguageHelper.commentChar) +
            this.currentLanguageHelper.commentEnd;
      },
    },
    components: {
      CodeLine,
    },
  };
</script>

// src/components/CommentBlock.tsx
import { useMemo } from "react";
import { useAppContext } from "../AppContext";
import { center } from "../util";
import CodeLine from "./CodeLine";
import { formatCodeElements } from "./FormatCode";

export default function CommentBlock({ comment }: { comment: string }) {
  const { languageHelper } = useAppContext();

  const lines = useMemo(() => comment.split("\n"), [comment]);

  const longestLine = useMemo(() => Math.max(...lines.map((str: string) => str.length)), [lines]);

  const comments = useMemo(() => {
    return lines.map((str: string) => {
      const centered = center(str, longestLine);
      return {
        prefix: `${languageHelper.commentChar} `,
        content: centered,
        suffix: ` ${languageHelper.commentChar}`,
      };
    });
  }, [lines, longestLine, languageHelper]);

  const header = useMemo(
    () => languageHelper.commentEnd + new Array(longestLine + 4).join(languageHelper.commentChar),
    [longestLine, languageHelper],
  );

  const footer = useMemo(
    () => new Array(longestLine + 4).join(languageHelper.commentChar) + languageHelper.commentEnd,
    [longestLine, languageHelper],
  );

  return (
    <div className="comment-block">
      <CodeLine>
        <span className="comment">{header}</span>
      </CodeLine>
      {comments.map((c, index) => (
        <CodeLine key={index}>
          <span className="comment">
            {c.prefix}
            {formatCodeElements(c.content)}
            {c.suffix}
          </span>
        </CodeLine>
      ))}
      <CodeLine>
        <span className="comment">{footer}</span>
      </CodeLine>
    </div>
  );
}
