// src/views/_curriculum_vitae.vue
<template>
  <div class="curriculum-vitae">
    <CodeLine>
      <span class="storage-type" v-if="isJs">const</span>
      <span class="white-space space" v-if="isJs"></span>
      <VariableName name="curriculumVitae" />
      <span class="variable">{{ title }}</span>
      <span class="keyword" v-if="isTs">:</span>
      <span class="white-space space"></span>
      <span class="expression" v-if="isTs">(</span>
      <span class="type class" v-if="isTs">Job</span>
      <span class="white-space space" v-if="isTs"></span>
      <span class="keyword" v-if="isTs">|</span>
      <span class="white-space space" v-if="isTs"></span>
      <span class="type class" v-if="isTs">Education</span>
      <span class="expression" v-if="isTs">)[]</span>
      <span class="white-space space" v-if="isTs"></span>
      <span class="expression">=</span>
      <span class="white-space space"></span>
      <span class="expression">[</span>
    </CodeLine>
    <template v-for="(entry, index) in data">
      <component
        :is="entry.company ? 'Job' : 'Education'"
        :key="`entry-${index}`"
        :data="entry"
        :isLast="index === data.length - 1"
      />
    </template>
    <CodeLine>
      <span class="expression">]</span>
      <span class="expression" v-if="isJs">;</span>
    </CodeLine>
  </div>
</template>

<script lang="ts">
import VariableName from './_variable_name.vue';
import CodeLine from './_code_line.vue';
import Job from './_job.vue';
import Education from './_education.vue';

export default {
  props: ['data'],
  components: {
    CodeLine,
    Job,
    Education,
    VariableName,
  },
};
</script>

// src/components/CurriculumVitae.tsx
import { useAppContext } from "../AppContext";
import type { Education as EducationType, Job as JobType } from "../data_types";
import CodeLine from "./CodeLine";
import Education from "./Education";
import Job from "./Job";
import VariableName from "./VariableName";

export default function CurriculumVitae({ data }: { data: (JobType | EducationType)[] }) {
  const { isJs, isTs } = useAppContext();

  return (
    <div className="curriculum-vitae">
      <CodeLine>
        {isJs && <span className="storage-type">const</span>}
        {isJs && <span className="white-space space"></span>}
        <VariableName name="curriculumVitae" />
        {isTs && <span className="keyword">:</span>}
        {isTs && <span className="white-space space"></span>}
        {isTs && <span className="expression">(</span>}
        {isTs && <span className="type class">Job</span>}
        {isTs && <span className="white-space space"></span>}
        {isTs && <span className="keyword">|</span>}
        {isTs && <span className="white-space space"></span>}
        {isTs && <span className="type class">Education</span>}
        {isTs && <span className="expression">)[]</span>}
        {isTs && <span className="white-space space"></span>}
        <span className="expression">=</span>
        <span className="white-space space"></span>
        <span className="expression">[</span>
      </CodeLine>
      {data.map((entry, index) =>
        "company" in entry ? (
          <Job key={index} data={entry as JobType} isLast={index === data.length - 1} />
        ) : (
          <Education key={index} data={entry as EducationType} isLast={index === data.length - 1} />
        ),
      )}
      <CodeLine>
        <span className="expression">]</span>
        {isJs && <span className="expression">;</span>}
      </CodeLine>
    </div>
  );
}
