// src/views/_job.vue
<template>
  <Stage
    class="job"
    :abbreviation="`${startYear}-${endYear} - ${data.company} - ${mainPosition}`"
    :data="data"
    :isLast="isLast"
  >
    <CodeLine>
      <Tab/><Tab/>
      <span class="variable">company</span>
      <span class="expression">:</span>
      <span class="white-space space"></span>
      <String :value="data.company"></String>
      <span class="expression">,</span>
    </CodeLine>
    <CodeLine>
      <Tab/><Tab/>
      <VariableName name="remote"/>
      <span class="expression">:</span>
      <span class="white-space space"></span>
      <Boolean :value="data.remote"></Boolean>
      <span class="expression">,</span>
    </CodeLine>
    <template v-if="Array.isArray(data.position)">
      <CodeLine>
        <Tab/><Tab/>
      <VariableName name="position"/>
        <span class="expression">:</span>
        <span class="white-space space"></span>
        <span class="expression">[</span>
      </CodeLine>
      <CodeLine v-for="position in data.position" :key="position">
        <Tab/><Tab/><Tab/>
        <String :value="position"></String>
        <span class="expression">,</span>
      </CodeLine>
      <CodeLine>
        <Tab/><Tab/>
        <span class="expression">],</span>
      </CodeLine>
    </template>
    <template v-else>
      <CodeLine>
        <Tab/><Tab/>
        <VariableName name="position"/>
        <span class="expression">:</span>
        <span class="white-space space"></span>
        <String :value="data.position"></String>
        <span class="expression">,</span>
      </CodeLine>
    </template>
  </Stage>
</template>

<script lang="ts">
  import CodeLine from './_code_line.vue';
  import Tab from './_tab.vue';
  import String from './_string.vue';
  import Boolean from './_boolean.vue';
  import Stage from './_stage.vue';
  import VariableName from './_variable_name.vue';

  export default {
    props: [
      'data',
      'isLast',
    ],
    components: {
      CodeLine,
      Tab,
      String,
      Boolean,
      Stage,
      VariableName,
    },
    computed: {
      startYear() {
        return this.data.startsAt.getFullYear();
      },
      endYear() {
        return this.data.endsAt ? this.data.endsAt.getFullYear() : ' now';
      },
      mainPosition() {
        const position = Array.isArray(this.data.position)
          ? this.data.position[0]
          : this.data.position
        ;
        const remote = this.data.remote ? '(remote) ' : '';
        return remote + position;
      },
    },
  };
</script>

// src/components/Job.tsx
import { useMemo } from "react";
import type { Job as JobType } from "../data_types";
import BooleanValue from "./BooleanValue";
import CodeLine from "./CodeLine";
import Stage from "./Stage";
import StringValue from "./StringValue";
import Tab from "./Tab";
import VariableName from "./VariableName";

export default function Job({ data, isLast }: { data: JobType; isLast: boolean }) {
  const startYear = data.startsAt.getFullYear();
  const endYear = data.endsAt ? data.endsAt.getFullYear() : " now";

  const mainPosition = useMemo(() => {
    const position = Array.isArray(data.position) ? data.position[0] : data.position;
    const remote = data.remote ? "(remote) " : "";
    return remote + position;
  }, [data]);

  return (
    <Stage
      className="job"
      abbreviation={`${startYear}-${endYear} - ${data.company} - ${mainPosition}`}
      data={data}
      isLast={isLast}
    >
      <CodeLine>
        <Tab />
        <Tab />
        <span className="variable">company</span>
        <span className="expression">:</span>
        <span className="white-space space"></span>
        <StringValue value={data.company} />
        <span className="expression">,</span>
      </CodeLine>
      <CodeLine>
        <Tab />
        <Tab />
        <VariableName name="remote" />
        <span className="expression">:</span>
        <span className="white-space space"></span>
        <BooleanValue value={data.remote} />
        <span className="expression">,</span>
      </CodeLine>
      {Array.isArray(data.position) ? (
        <>
          <CodeLine>
            <Tab />
            <Tab />
            <VariableName name="position" />
            <span className="expression">:</span>
            <span className="white-space space"></span>
            <span className="expression">[</span>
          </CodeLine>
          {data.position.map((position) => (
            <CodeLine key={position}>
              <Tab />
              <Tab />
              <Tab />
              <StringValue value={position} />
              <span className="expression">,</span>
            </CodeLine>
          ))}
          <CodeLine>
            <Tab />
            <Tab />
            <span className="expression">],</span>
          </CodeLine>
        </>
      ) : (
        <CodeLine>
          <Tab />
          <Tab />
          <VariableName name="position" />
          <span className="expression">:</span>
          <span className="white-space space"></span>
          <StringValue value={data.position} />
          <span className="expression">,</span>
        </CodeLine>
      )}
    </Stage>
  );
}
