// src/views/_variable.vue
<template>
  <CodeLine>
    <span class="storage-type" v-if="isJs">const</span>
    <span class="white-space space" v-if="isJs"></span>
    <VariableName :name="name" :length="length"/>
    <span class="variable">{{displayName}}</span>
    <template v-if="padLeft">
      <span v-for="i in padLeft" :key="i" class="white-space space"></span>
    </template>
    <template v-if="type && isTs">
      <span class="keyword">:</span>
      <span class="white-space space"></span>
      <span class="type class">{{type}}</span>
    </template>
    <span class="white-space space"></span>
    <span class="keyword">=</span>
    <span class="white-space space"></span>
    <slot>
      <span class="constant">
        {{currentLanguageHelper.undefined}}
      </span>
    </slot>
    <span class="expression" v-if="isJs">;</span>
  </CodeLine>
</template>

<script lang="ts">
  import CodeLine from './_code_line.vue';
  import VariableName from './_variable_name.vue';

  export default {
    props: [
      'name',
      'length',
      'type',
    ],
    components: {
      CodeLine,
      VariableName,
    },
  };
</script>

// src/components/Variable.tsx
import type { ReactNode } from "react";
import { useAppContext } from "../AppContext";
import CodeLine from "./CodeLine";
import VariableName from "./VariableName";

export default function Variable({
  name,
  length,
  type,
  children,
}: {
  name: string;
  length?: number;
  type?: string;
  children?: ReactNode;
}) {
  const { isJs, isTs, languageHelper } = useAppContext();

  return (
    <CodeLine>
      {isJs && <span className="storage-type">const</span>}
      {isJs && <span className="white-space space"></span>}
      <VariableName name={name} length={length} />
      {type && isTs && (
        <>
          <span className="keyword">:</span>
          <span className="white-space space"></span>
          <span className="type class">{type}</span>
        </>
      )}
      <span className="white-space space"></span>
      <span className="keyword">=</span>
      <span className="white-space space"></span>
      {children || <span className="constant">{languageHelper.undefined}</span>}
      {isJs && <span className="expression">;</span>}
    </CodeLine>
  );
}
