// src/views/_variable_name.vue
<template>
  <span class="variable">
    {{ displayName
    }}<template v-if="padLeft">
      <span v-for="i in padLeft" :key="i" class="white-space space"></span>
    </template>
  </span>
</template>

<script lang="ts">
export default {
  props: ['name', 'length'],
  computed: {
    displayName() {
      return this.snakeCase(this.name);
    },
    padLeft() {
      if (this.length !== undefined && this.displayName.length < this.length) {
        return this.length - this.displayName.length;
      }
      return false;
    },
  },
};
</script>

// src/components/VariableName.tsx
import { useMemo } from "react";
import { useAppContext } from "../AppContext";

export default function VariableName({ name, length }: { name: string; length?: number }) {
  const { snakeCase } = useAppContext();

  const displayName = useMemo(() => snakeCase(name), [name, snakeCase]);

  const padLeft = useMemo(() => {
    if (length !== undefined && displayName.length < length) {
      return length - displayName.length;
    }
    return 0;
  }, [length, displayName]);

  return (
    <span className="variable">
      {displayName}
      {padLeft > 0 &&
        Array.from({ length: padLeft }, (_, i) => (
          <span key={i} className="white-space space"></span>
        ))}
    </span>
  );
}
